### ISSUE TITLE
File schema with an owner

### ISSUE THREAD

**Issue by ccorcos** [aldeed/meteor-cfs-autoform#16]
I want to limit the people who are able to view / download a file based on their ownership of the file. Thus I'm trying to create a schema with an autovalue. Check out the `Receipts` collection below.

```
@Records = new Mongo.Collection "records"

@Receipts = new FS.Collection "receipts", 
  stores: [new FS.Store.GridFS("receiptStore")]

@Receipts.allow
  download: (userId, doc) -> userId is doc.ownerId
  fetch: ['ownerId']

@Receipts.attachSchema new SimpleSchema
  ownerId:
    type: String,
    label: "Author"
    autoValue: -> Meteor.userId()

@Records.attachSchema new SimpleSchema
  ownerId:
    type: String,
    label: "Author"
    autoValue: -> Meteor.userId()
  createdAt:
    type: Date
    autoValue: -> new Date
  amount:
    type: Number
    label: "Amount"
    min: 0
  memo:
    type: String
    label: "Memo"
    optional: true
  receiptId:
    type: String
    optional: true
    autoform:
      afFieldInput:
        type: "cfs-file"
        collection: "receipts"
```

I'm ending up with this error:

`TypeError: Object #<EventEmitter> has no method 'attachSchema'`

apparently `Receipts` is an EventEmitter. 

Anyways, is there an easy way of implementing this functionality?
